### ISSUE TITLE
msgs key in tx gives wrong signature

### ISSUE THREAD

**Issue by patrickwieth** [cosmos/sig#12] opened 2020-04-04 17:22 UTC
in readme.MD this:

const tx = {
    fee:  {
        amount: [{ amount: '0', denom: '' }],
        gas:    '10000'
    },
    memo: '',
    msgs: [{
        type:  'cosmos-sdk/Send',
        value: {
            inputs:  [{
                address: 'cosmos1qperwt9wrnkg5k9e5gzfgjppzpqhyav5j24d66',
                coins:   [{ amount: '1', denom: 'STAKE' }]
            }],
            outputs: [{
                address: 'cosmos1yeckxz7tapz34kjwnjxvmxzurerquhtrmxmuxt',
                coins:   [{  amount: '1', denom: 'STAKE' }]
            }]
        }
    }]
};

should be:

const tx = {
    fee:  {
        amount: [{ amount: '0', denom: '' }],
        gas:    '10000'
    },
    memo: '',
    msg: [{
        type:  'cosmos-sdk/Send',
        value: {
            inputs:  [{
                address: 'cosmos1qperwt9wrnkg5k9e5gzfgjppzpqhyav5j24d66',
                coins:   [{ amount: '1', denom: 'STAKE' }]
            }],
            outputs: [{
                address: 'cosmos1yeckxz7tapz34kjwnjxvmxzurerquhtrmxmuxt',
                coins:   [{  amount: '1', denom: 'STAKE' }]
            }]
        }
    }]
};

**Comment by motopig** [comment] 2020-05-15 08:31
msg struct changed，but docs not update, check this out 
`let tx = {

		msg: [

			{

				type: "cosmos-sdk/MsgSend",

				value: {

					amount: [

						{

							amount: String(3),

							denom: "stake"

						}

					],

					from_address: "",

					to_address: ""

				}

			}

		],

		fee: { amount: [ { amount: String(1), denom: "stake" } ], gas: String(200000) },

		memo: ""

    };`

**Comment by jordansexton** [comment] 2020-06-02 08:09
Possibly a duplicate of #6 and therefore closed by 4fef8dd. Please reopen if needed.

**Comment by patrickwieth** [comment] 2020-06-02 09:24
motopig got it right. 

The readme.MD has "tx.msgs" as key, should be "tx.msg". Just try it out, the signature produced when using msgs will be wrong and give "signature verification failure", whereas when I change the example from the readme.MD to "tx.msg: ...." then the tx goes through.

**Comment by jordansexton** [comment] 2020-06-02 18:59
Thanks @patrickwieth. I'll update the docs accordingly.

**Closed** 2020-06-02 19:51 UTC
